const std = @import("std");

fn lessThanString(_: void, lhs: []const u8, rhs: []const u8) bool {
    return std.mem.order(u8, lhs, rhs) == .lt;
}

fn generateJsonCorpusTests(b: *std.Build) std.Build.LazyPath {
    const corpus_dir = b.pathFromRoot("tests/corpus/json");
    const io = b.graph.io;

    var names = std.array_list.Managed([]const u8).init(b.allocator);
    defer {
        for (names.items) |name| b.allocator.free(name);
        names.deinit();
    }

    var dir = std.Io.Dir.cwd().openDir(io, corpus_dir, .{ .iterate = true }) catch @panic("failed to open JSON corpus directory");
    defer dir.close(io);

    var iter = dir.iterate();
    while ((iter.next(io) catch @panic("failed to read JSON corpus directory"))) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".json")) continue;
        names.append(b.allocator.dupe(u8, entry.name) catch @panic("OOM")) catch @panic("OOM");
    }

    std.sort.heap([]const u8, names.items, {}, lessThanString);

    var out: std.Io.Writer.Allocating = .init(b.allocator);
    defer out.deinit();

    out.writer.writeAll(
        \\// Generated by build.zig from tests/corpus/json.
        \\const support = @import("json_corpus_support");
        \\
    ) catch @panic("failed to write JSON corpus test prologue");

    for (names.items) |name| {
        const rel_path = std.fmt.allocPrint(b.allocator, "tests/corpus/json/{s}", .{name}) catch @panic("OOM");
        defer b.allocator.free(rel_path);

        out.writer.print(
            \\test "json corpus: {s}" {{
            \\    try support.expectRoundTripMatches("{s}", @embedFile("{s}"));
            \\}}
            \\
        ,
            .{
                name,
                name,
                b.pathFromRoot(rel_path),
            },
        ) catch @panic("failed to write JSON corpus test case");
    }

    const generated = b.addWriteFiles();
    return generated.add("json_corpus_generated.zig", out.written());
}

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const zig_toml_dep = b.dependency("toml", .{
        .target = target,
        .optimize = optimize,
    });
    const zbor_dep = b.dependency("zbor", .{
        .target = target,
        .optimize = optimize,
    });
    const zbench_dep = b.dependency("zbench", .{
        .target = target,
        .optimize = optimize,
    });
    const zig_yaml_mod = b.createModule(.{
        .root_source_file = b.path("vendor/zig-yaml/src/lib.zig"),
        .target = target,
        .optimize = optimize,
    });

    // The package itself is just `src/root.zig`; tests and benchmarks import it.
    const zerde_mod = b.addModule("zerde", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
    });

    // `zig build test` exercises the library as a package module.
    const tests = b.addTest(.{
        .root_module = zerde_mod,
    });

    const json_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/json_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zerde", .module = zerde_mod },
        },
    });
    const json_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateJsonCorpusTests(b),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "json_corpus_support", .module = json_corpus_support_mod },
        },
    });
    const json_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/json_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "json_corpus_generated", .module = json_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("json_tests", json_tests_mod);

    const run_tests = b.addRunArtifact(tests);

    const test_step = b.step("test", "Run zerde tests");
    test_step.dependOn(&run_tests.step);

    // Benchmarks live in a separate executable so they can use a different root file.
    const bench_exe = b.addExecutable(.{
        .name = "zerde-bench",
        .root_module = b.createModule(.{
            .root_source_file = b.path("bench/bench.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zerde", .module = zerde_mod },
                .{ .name = "zig_toml", .module = zig_toml_dep.module("toml") },
                .{ .name = "zbor", .module = zbor_dep.module("zbor") },
                .{ .name = "zbench", .module = zbench_dep.module("zbench") },
                .{ .name = "zig_yaml", .module = zig_yaml_mod },
            },
        }),
    });
    b.installArtifact(bench_exe);

    const run_bench = b.addRunArtifact(bench_exe);
    if (b.args) |args| run_bench.addArgs(args);

    const run_bench_json = b.addRunArtifact(bench_exe);
    run_bench_json.addArg("json");

    const run_bench_toml = b.addRunArtifact(bench_exe);
    run_bench_toml.addArg("toml");

    const run_bench_cbor = b.addRunArtifact(bench_exe);
    run_bench_cbor.addArg("cbor");

    const run_bench_yaml = b.addRunArtifact(bench_exe);
    run_bench_yaml.addArg("yaml");

    const bench_step = b.step("bench", "Run JSON, TOML, CBOR, and YAML benchmarks");
    bench_step.dependOn(&run_bench.step);

    const bench_json_step = b.step("bench-json", "Run JSON benchmark against std.json");
    bench_json_step.dependOn(&run_bench_json.step);

    const bench_toml_step = b.step("bench-toml", "Run TOML benchmark against zig-toml");
    bench_toml_step.dependOn(&run_bench_toml.step);

    const bench_cbor_step = b.step("bench-cbor", "Run CBOR benchmark against zbor");
    bench_cbor_step.dependOn(&run_bench_cbor.step);

    const bench_yaml_step = b.step("bench-yaml", "Run YAML benchmark against zig-yaml");
    bench_yaml_step.dependOn(&run_bench_yaml.step);
}
