const std = @import("std");

fn lessThanString(_: void, lhs: []const u8, rhs: []const u8) bool {
    return std.mem.order(u8, lhs, rhs) == .lt;
}

fn addWasmExample(
    b: *std.Build,
    comptime name: []const u8,
    comptime path: []const u8,
    optimize: std.builtin.OptimizeMode,
    zerde_mod: *std.Build.Module,
) *std.Build.Step.Compile {
    const wasm_target = b.resolveTargetQuery(.{
        .cpu_arch = .wasm32,
        .os_tag = .freestanding,
    });

    const artifact = b.addExecutable(.{
        .name = name,
        .root_module = b.createModule(.{
            .root_source_file = b.path(path),
            .target = wasm_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zerde", .module = zerde_mod },
            },
        }),
    });

    artifact.entry = .disabled;
    artifact.export_memory = true;
    artifact.rdynamic = true;
    return artifact;
}

fn addNativeExample(
    b: *std.Build,
    comptime name: []const u8,
    comptime path: []const u8,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zerde_mod: *std.Build.Module,
) *std.Build.Step.Compile {
    return b.addExecutable(.{
        .name = name,
        .root_module = b.createModule(.{
            .root_source_file = b.path(path),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zerde", .module = zerde_mod },
            },
        }),
    });
}

fn generateCorpusTests(
    b: *std.Build,
    comptime format_name: []const u8,
    comptime extension: []const u8,
    comptime support_import_name: []const u8,
) std.Build.LazyPath {
    const corpus_dir = b.pathFromRoot(std.fmt.comptimePrint("tests/corpus/{s}", .{format_name}));
    const io = b.graph.io;

    var names = std.array_list.Managed([]const u8).init(b.allocator);
    defer {
        for (names.items) |name| b.allocator.free(name);
        names.deinit();
    }

    var dir = std.Io.Dir.cwd().openDir(io, corpus_dir, .{ .iterate = true }) catch @panic("failed to open JSON corpus directory");
    defer dir.close(io);

    var iter = dir.iterate();
    while ((iter.next(io) catch @panic("failed to read JSON corpus directory"))) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, extension)) continue;
        names.append(b.allocator.dupe(u8, entry.name) catch @panic("OOM")) catch @panic("OOM");
    }

    std.sort.heap([]const u8, names.items, {}, lessThanString);

    var out: std.Io.Writer.Allocating = .init(b.allocator);
    defer out.deinit();

    out.writer.writeAll(std.fmt.comptimePrint(
        \\// Generated by build.zig from tests/corpus/{s}.
        \\const support = @import("{s}");
        \\
    , .{ format_name, support_import_name })) catch @panic("failed to write corpus test prologue");

    for (names.items) |name| {
        const rel_path = std.fmt.allocPrint(b.allocator, "tests/corpus/{s}/{s}", .{ format_name, name }) catch @panic("OOM");
        defer b.allocator.free(rel_path);

        out.writer.print(
            \\test "{s} corpus: {s}" {{
            \\    try support.expectRoundTripMatches("{s}", @embedFile("{f}"));
            \\}}
            \\
        ,
            .{
                format_name,
                name,
                name,
                std.zig.fmtString(b.pathFromRoot(rel_path)),
            },
        ) catch @panic("failed to write corpus test case");
    }

    const generated = b.addWriteFiles();
    return generated.add(std.fmt.comptimePrint("{s}_corpus_generated.zig", .{format_name}), out.written());
}

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const zig_toml_dep = b.dependency("toml", .{
        .target = target,
        .optimize = optimize,
    });
    const zbor_dep = b.dependency("zbor", .{
        .target = target,
        .optimize = optimize,
    });
    const zbench_dep = b.dependency("zbench", .{
        .target = target,
        .optimize = optimize,
    });
    const zig_bson_mod = b.createModule(.{
        .root_source_file = b.path("vendor/zig-bson/src/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    const bufzilla_mod = b.createModule(.{
        .root_source_file = b.path("vendor/bufzilla/src/lib.zig"),
        .target = target,
        .optimize = optimize,
    });
    const zig_msgpack_mod = b.createModule(.{
        .root_source_file = b.path("vendor/msgpack-zig/src/msgpack.zig"),
        .target = target,
        .optimize = optimize,
    });
    const zig_yaml_mod = b.createModule(.{
        .root_source_file = b.path("vendor/zig-yaml/src/lib.zig"),
        .target = target,
        .optimize = optimize,
    });

    // The package itself is just `src/root.zig`; tests and benchmarks import it.
    const zerde_mod = b.addModule("zerde", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
    });

    const tests_root_mod = b.createModule(.{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
    });

    // `zig build test` exercises the library as a package module.
    const tests = b.addTest(.{
        .root_module = tests_root_mod,
    });

    const corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });

    const bin_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/bin_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus_support", .module = corpus_support_mod },
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const bin_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "bin", ".bin", "bin_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "bin_corpus_support", .module = bin_corpus_support_mod },
        },
    });
    const bin_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/bin_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "bin_corpus_generated", .module = bin_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("bin_tests", bin_tests_mod);

    const json_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/json_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const json_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "json", ".json", "json_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "json_corpus_support", .module = json_corpus_support_mod },
        },
    });
    const json_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/json_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "json_corpus_generated", .module = json_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("json_tests", json_tests_mod);

    const toml_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/toml_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus_support", .module = corpus_support_mod },
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const toml_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "toml", ".toml", "toml_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "toml_corpus_support", .module = toml_corpus_support_mod },
        },
    });
    const toml_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/toml_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "toml_corpus_generated", .module = toml_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("toml_tests", toml_tests_mod);

    const yaml_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/yaml_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus_support", .module = corpus_support_mod },
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const yaml_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "yaml", ".yaml", "yaml_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "yaml_corpus_support", .module = yaml_corpus_support_mod },
        },
    });
    const yaml_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/yaml_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "yaml_corpus_generated", .module = yaml_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("yaml_tests", yaml_tests_mod);

    const cbor_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/cbor_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus_support", .module = corpus_support_mod },
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const cbor_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "cbor", ".cbor", "cbor_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "cbor_corpus_support", .module = cbor_corpus_support_mod },
        },
    });
    const cbor_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/cbor_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "cbor_corpus_generated", .module = cbor_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("cbor_tests", cbor_tests_mod);

    const msgpack_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/msgpack_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus_support", .module = corpus_support_mod },
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const msgpack_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "msgpack", ".msgpack", "msgpack_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "msgpack_corpus_support", .module = msgpack_corpus_support_mod },
        },
    });
    const msgpack_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/msgpack_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "msgpack_corpus_generated", .module = msgpack_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("msgpack_tests", msgpack_tests_mod);

    const bson_corpus_support_mod = b.createModule(.{
        .root_source_file = b.path("tests/bson_corpus_support.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "corpus_support", .module = corpus_support_mod },
            .{ .name = "zerde", .module = tests_root_mod },
        },
    });
    const bson_corpus_generated_mod = b.createModule(.{
        .root_source_file = generateCorpusTests(b, "bson", ".bson", "bson_corpus_support"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "bson_corpus_support", .module = bson_corpus_support_mod },
        },
    });
    const bson_tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/bson_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "bson_corpus_generated", .module = bson_corpus_generated_mod },
        },
    });
    tests.root_module.addImport("bson_tests", bson_tests_mod);

    const run_tests = b.addRunArtifact(tests);

    const test_step = b.step("test", "Run zerde tests");
    test_step.dependOn(&run_tests.step);

    const examples_step = b.step("examples", "Compile native and WASM examples");
    inline for (.{
        .{ "json-roundtrip", "examples/json_roundtrip.zig" },
        .{ "toml-roundtrip", "examples/toml_roundtrip.zig" },
        .{ "yaml-roundtrip", "examples/yaml_roundtrip.zig" },
        .{ "cbor-roundtrip", "examples/cbor_roundtrip.zig" },
        .{ "bson-roundtrip", "examples/bson_roundtrip.zig" },
        .{ "msgpack-roundtrip", "examples/msgpack_roundtrip.zig" },
        .{ "bin-roundtrip", "examples/bin_roundtrip.zig" },
    }) |example| {
        const artifact = addNativeExample(b, example[0], example[1], target, optimize, zerde_mod);
        const install = b.addInstallArtifact(artifact, .{});
        examples_step.dependOn(&install.step);
    }

    inline for (.{
        .{ "wasm-bin-bridge", "examples/wasm_bin_bridge.zig" },
        .{ "wasm-json-bridge", "examples/wasm_json_bridge.zig" },
        .{ "wasm-yaml-bridge", "examples/wasm_yaml_bridge.zig" },
        .{ "wasm-msgpack-bridge", "examples/wasm_msgpack_bridge.zig" },
    }) |example| {
        const artifact = addWasmExample(b, example[0], example[1], optimize, zerde_mod);
        const install = b.addInstallArtifact(artifact, .{});
        examples_step.dependOn(&install.step);
    }

    // Benchmarks live in a separate executable so they can use a different root file.
    const bench_exe = b.addExecutable(.{
        .name = "zerde-bench",
        .root_module = b.createModule(.{
            .root_source_file = b.path("bench/bench.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "bufzilla", .module = bufzilla_mod },
                .{ .name = "zerde", .module = zerde_mod },
                .{ .name = "zig_bson", .module = zig_bson_mod },
                .{ .name = "zig_msgpack", .module = zig_msgpack_mod },
                .{ .name = "zig_toml", .module = zig_toml_dep.module("toml") },
                .{ .name = "zbor", .module = zbor_dep.module("zbor") },
                .{ .name = "zbench", .module = zbench_dep.module("zbench") },
                .{ .name = "zig_yaml", .module = zig_yaml_mod },
            },
        }),
    });
    b.installArtifact(bench_exe);

    const run_bench = b.addRunArtifact(bench_exe);
    if (b.args) |args| run_bench.addArgs(args);

    const bench_build_step = b.step("bench-build", "Compile benchmark harness without running it");
    bench_build_step.dependOn(&bench_exe.step);

    const run_bench_json = b.addRunArtifact(bench_exe);
    run_bench_json.addArg("json");

    const run_bench_toml = b.addRunArtifact(bench_exe);
    run_bench_toml.addArg("toml");

    const run_bench_cbor = b.addRunArtifact(bench_exe);
    run_bench_cbor.addArg("cbor");

    const run_bench_bson = b.addRunArtifact(bench_exe);
    run_bench_bson.addArg("bson");

    const run_bench_bin = b.addRunArtifact(bench_exe);
    run_bench_bin.addArg("bin");

    const run_bench_msgpack = b.addRunArtifact(bench_exe);
    run_bench_msgpack.addArg("msgpack");

    const run_bench_yaml = b.addRunArtifact(bench_exe);
    run_bench_yaml.addArg("yaml");

    const run_bench_wasm = b.addRunArtifact(bench_exe);
    run_bench_wasm.addArg("wasm");

    const bench_step = b.step("bench", "Run binary, JSON, TOML, CBOR, BSON, MessagePack, YAML, and WASM benchmarks");
    bench_step.dependOn(&run_bench.step);

    const bench_json_step = b.step("bench-json", "Run JSON benchmark against std.json");
    bench_json_step.dependOn(&run_bench_json.step);

    const bench_toml_step = b.step("bench-toml", "Run TOML benchmark against zig-toml");
    bench_toml_step.dependOn(&run_bench_toml.step);

    const bench_cbor_step = b.step("bench-cbor", "Run CBOR benchmark against zbor");
    bench_cbor_step.dependOn(&run_bench_cbor.step);

    const bench_bson_step = b.step("bench-bson", "Run BSON benchmark against zig-bson");
    bench_bson_step.dependOn(&run_bench_bson.step);

    const bench_bin_step = b.step("bench-bin", "Run binary benchmark against bufzilla");
    bench_bin_step.dependOn(&run_bench_bin.step);

    const bench_msgpack_step = b.step("bench-msgpack", "Run MessagePack benchmark against msgpack.zig");
    bench_msgpack_step.dependOn(&run_bench_msgpack.step);

    const bench_yaml_step = b.step("bench-yaml", "Run YAML benchmark against zig-yaml");
    bench_yaml_step.dependOn(&run_bench_yaml.step);

    const bench_wasm_step = b.step("bench-wasm", "Run WASM helper benchmark against the direct binary path");
    bench_wasm_step.dependOn(&run_bench_wasm.step);
}
